package frc.robot.state.sequencer;

public enum Sequence {
    RESET,

    INTAKE_ALGAE_L2,
    INTAKE_ALGAE_L3,
    INTAKE_ALGAE_FLOOR,
    SHOOT_ALGAE,
    HANDOFF_ALGAE,
    
    INTAKE_CORAL_FEEDER,
    INTAKE_CORAL_FLOOR,
    INTAKE_CORAL_FLOOR_UPRIGHT,
    SCORE_CORAL_L1,
    SCORE_CORAL_L2,
    SCORE_CORAL_L3,
    SCORE_CORAL_L4,

    UNSTUCK_ELEVATOR
}
